name: PokéScan

options:
  bundleIdPrefix: com.guicf
  deploymentTarget:
    iOS: '15.0'

targets:
  PokéScan:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.guicf.PokeScan
        SWIFT_VERSION: 5.0
        GENERATE_INFOPLIST_FILE: YES

schemes:
  PokéScan:
    build:
      targets:
        PokéScan: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
